In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2)

In [3]:
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
b=np.array([[7,4,1],[8,5,2],[9,6,3]])
b

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [5]:
# element wise multiplication
a*b

array([[ 7, 16,  7],
       [16, 25, 16],
       [27, 36, 27]])

In [6]:
# Matric Multiplication
# Dot Product
np.dot(a,b)

array([[102,  66,  30],
       [126,  81,  36],
       [150,  96,  42]])