## Zeros()

In [1]:
import numpy as np

In [2]:
zarr = np.zeros(10)

In [3]:
print(zarr) #we get float zeros because inbuilt fuctionality of zeros function gives only float

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
zarr = zarr.astype(int)  #converts float 0 into int

In [6]:
print(zarr)

[0 0 0 0 0 0 0 0 0 0]


In [7]:
l = [1.2,2.3,3.4,4.5]

In [10]:
l=np.array(l)

In [13]:
print(l)

[1.2 2.3 3.4 4.5]


In [14]:
l=l.astype(int)

In [15]:
print(l)

[1 2 3 4]


## ones()

In [16]:
oarr=np.ones(10)

In [17]:
print(oarr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
oarr=oarr.astype(int)

In [19]:
print(oarr)

[1 1 1 1 1 1 1 1 1 1]


## full()

In [20]:
farr=np.full(10,5)

In [21]:
print(farr)

[5 5 5 5 5 5 5 5 5 5]


In [22]:
farr=farr.astype(float)

In [23]:
print(farr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Sclaer operation

In [2]:
mat = np.array([[1,2,3],[4,5,6]])

In [3]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [4]:
mat = mat+2
print(mat)

[[3 4 5]
 [6 7 8]]
