In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])

In [4]:
print(arr)

[1 2 3 4]


In [5]:
l=[5,6,7,8,9]

In [7]:
l=np.array(l)

In [10]:
print(l)

[5 6 7 8 9]


In [11]:
print(l.ndim)

1


In [13]:
td_arr=np.array([[1,2,3],[7,8,9]])

In [14]:
print(td_arr.ndim)

2


In [15]:
trd_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [16]:
print(trd_arr.ndim)

3


In [17]:
print(trd_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print(td_arr)

[[1 2 3]
 [7 8 9]]


In [19]:
print(td_arr[1][1])

8


In [20]:
print(td_arr[1][2])

9


In [21]:
print(td_arr[0][2])

3


In [22]:
print(td_arr[0][0])

1


In [24]:
print(trd_arr[0][1][1])

5


In [25]:
print(trd_arr[1][1][1])

11


In [26]:
print(trd_arr[1][0][2])

9


In [27]:
print(trd_arr[0])

[[1 2 3]
 [4 5 6]]


In [28]:
print(trd_arr[0][1])

[4 5 6]


In [29]:
print(trd_arr[0][1][2])

6


In [30]:
print(trd_arr[0,1,2])

6


In [31]:
print(trd_arr[0,1])

[4 5 6]


In [32]:
print(arr.shape)

(4,)


In [33]:
print(td_arr.shape)

(2, 3)


In [34]:
print(trd_arr.shape)

(2, 2, 3)


In [35]:
for i in arr:
    print(i)

1
2
3
4


In [36]:
for i in td_arr:
    print(i)

[1 2 3]
[7 8 9]


In [37]:
for i in td_arr:
    for j in i:
        print(j)

1
2
3
7
8
9


In [38]:
for i in trd_arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [39]:
for i in trd_arr:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [40]:
for i in trd_arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [41]:
for i in trd_arr:
    for j in i:
        for k in j:
            print(k,end=' ')
        print()
    print()

1 2 3 
4 5 6 

7 8 9 
10 11 12 

