In [1]:
import numpy as np
import cv2

In [3]:
black = np.zeros([150,200,1], 'uint8')

In [11]:
cv2.imshow("Black",black)
print(black[0,0,:])

# below two lines make sure, we can an image in new window
cv2.waitKey(0)
cv2.destroyAllWindows()

[0]


In [9]:
ones = np.ones([150,200,3],'uint8')

In [17]:
cv2.imshow("Ones",ones)
print(ones[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[1 1 1]


In [13]:
white = np.ones([150,200,3],'uint16')
white *= (2**16-1)  # this is for using maximum pixel values

In [16]:
cv2.imshow("White",white)
print(white[0,0,:])

# below two lines make sure, we can an image in new window
cv2.waitKey(0)
cv2.destroyAllWindows()

[65535 65535 65535]


In [18]:
color = ones.copy()
color[:,:] = (255,0,0)

In [19]:
cv2.imshow("Blue",color)
print(color[0,0,:])

# below two lines make sure, we can an image in new window
cv2.waitKey(0)
cv2.destroyAllWindows()

[255   0   0]


In [21]:
# shows all images at once

cv2.imshow("Black",black)
print(black[0,0,:])

cv2.imshow("Ones",ones)
print(ones[0,0,:])

cv2.imshow("White",white)
print(white[0,0,:])

cv2.imshow("Blue",color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255   0   0]
