In [3]:
import numpy as np
import pandas as pd
import sklearn
from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
from sklearn.linear_model import Perceptron

In [6]:
iris = datasets.load_iris()

X=iris.data
y=iris.target

X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [9]:
sdsc = StandardScaler()

standardized_X_test = sdsc.fit_transform(X_test)
standardized_X_train = sdsc.fit_transform(X_train)

In [10]:
standardized_X_test[:10]

array([[-0.14723465, -1.06345565,  0.00793077, -0.11339647],
       [-1.12879895, -0.10394679, -1.41960698, -1.47415411],
       [ 0.71163412, -0.10394679,  0.72169964,  0.97520964],
       [ 0.34354751, -0.34382401,  0.18637298,  0.02267929],
       [ 0.22085197, -0.34382401,  0.42429594,  0.15875506],
       [ 0.22085197, -0.10394679,  0.3648152 ,  0.15875506],
       [-1.12879895,  0.37580764, -1.65752994, -1.47415411],
       [-0.02453911, -0.10394679,  0.6622189 ,  0.70305811],
       [ 0.9570252 , -0.10394679,  0.60273816,  0.56698235],
       [-1.12879895, -2.50271894, -0.28947293, -0.385548  ]])

In [12]:
perceptron = Perceptron(max_iter=50,eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel()) # ravel will format data properly for model

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [13]:
y_pred = perceptron.predict(standardized_X_test)

In [14]:
print(y_test)

[1 0 2 1 1 1 0 2 1 1 2 0 2 1 1 2 2 2 0 2 2 2 1 1 1 0 2 0 0 0]


In [15]:
print(y_pred)

[1 0 2 1 1 1 0 2 2 1 1 0 2 1 0 1 2 1 0 2 2 2 1 2 0 0 2 0 0 0]


In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         8
           1       0.70      0.64      0.67        11
           2       0.80      0.73      0.76        11

    accuracy                           0.77        30
   macro avg       0.77      0.79      0.77        30
weighted avg       0.76      0.77      0.76        30

